---
name: sync-ec-cli-tasks

on:
  workflow_dispatch:
  schedule:
    # At 09:00 UTC on Tuesday
    - cron: '0 9 * * 1-5'

permissions:
  contents: read

jobs:
  sync-ec-cli-tasks:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

    - name: Harden Runner
      uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
      with:
        egress-policy: audit
        disable-telemetry: true

    - name: Checkout tekton-catalog
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      with:
        repository: enterprise-contract/tekton-catalog
        ref: main
        path: tekton-catalog

    - name: Checkout ec-cli
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      with:
        repository: enterprise-contract/ec-cli
        ref: main
        path: ec-cli

    - name: Sync tasks
      run: ./hack/sync-ec-cli-tasks.sh ../ec-cli
      working-directory: tekton-catalog
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
